version: '2'
services:
  caching-proxy:
    image: s3-proxy-cache
    container_name: s3-proxy-cache
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
